### ISSUE TITLE
rust-build does not seem to exist

### ISSUE THREAD

**Issue by senorsmile** [asaaki/rsenv#1]
In order to use the rsenv install, the documentation refers you to install rust-build, which now gives a 404.

**Comment by asaaki** [comment]
Sorry for the late answer. This project is not maintained anymore and was not feature complete (regarding rust-build).

Instead I highly recommend one of the following Rust version managers:

- [multirust](https://github.com/brson/multirust)

  The de-facto tool nowadays, I use it as the only tool right now.

- [rsvm](https://github.com/sdepold/rsvm)

  Haven't tested it, but since there is still some activity in the repo, I'd say you can still use it.
